package com.paic.ai.dao;

import com.paic.ai.dto.AiUser;

import java.util.List;
import java.util.Map;

public interface AiUserMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_user
     *
     * @mbggenerated
     */
    int insert(AiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_user
     *
     * @mbggenerated
     */
    AiUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_user
     *
     * @mbggenerated
     */
    List<AiUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ai_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AiUser record);

    AiUser selectByUserName(String accountNo);

    List<AiUser> queryUserList(Map<String, Object> paramMap);
}